name: meow
description: A new Flutter project

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  audioplayers: ^5.2.1
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  flutter_local_notifications: ^16.3.2
  charts_flutter: ^0.12.0
  intl: 0.17.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.14
  package_info_plus: ^4.1.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/backgrounds/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android: true
  ios: true