// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-3m-k2mrtqomXwZXbDaZAw5UTl7crSJU',
    appId: '1:814845484849:web:b03e5f4b1c84f645635a10',
    messagingSenderId: '814845484849',
    projectId: 'focusmate-edde4',
    authDomain: 'focusmate-edde4.firebaseapp.com',
    storageBucket: 'focusmate-edde4.firebasestorage.app',
    measurementId: 'G-QNQ7L1336T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0sye1UlH9BomDs7o3Fv8pkEHBpmlTc4',
    appId: '1:814845484849:android:028af3e247029ad1635a10',
    messagingSenderId: '814845484849',
    projectId: 'focusmate-edde4',
    storageBucket: 'focusmate-edde4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Rc7UL5QLGAlSQKXMbFAhPix51xFYwk0',
    appId: '1:814845484849:ios:159c48caaa634489635a10',
    messagingSenderId: '814845484849',
    projectId: 'focusmate-edde4',
    storageBucket: 'focusmate-edde4.firebasestorage.app',
    iosBundleId: 'com.example.meow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5Rc7UL5QLGAlSQKXMbFAhPix51xFYwk0',
    appId: '1:814845484849:ios:159c48caaa634489635a10',
    messagingSenderId: '814845484849',
    projectId: 'focusmate-edde4',
    storageBucket: 'focusmate-edde4.firebasestorage.app',
    iosBundleId: 'com.example.meow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-3m-k2mrtqomXwZXbDaZAw5UTl7crSJU',
    appId: '1:814845484849:web:4f30f4fe589d556d635a10',
    messagingSenderId: '814845484849',
    projectId: 'focusmate-edde4',
    authDomain: 'focusmate-edde4.firebaseapp.com',
    storageBucket: 'focusmate-edde4.firebasestorage.app',
    measurementId: 'G-66P8P46PB2',
  );
}
